# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e5d35b0419181050da74227ac3d0efec12694bae38a48680d628ebc32ff40cfd8958ec55ce21556f1c27a521b2aabd29dea5cb413b8c8106101e41c3442a22e

test:
  secret_key_base: 997fd2f6f4dab94803e094a35c8fdf3ebc2d3c00cec40d7f1c91091464fd225ddaed588b5d27b086ea9bc55594a7032666eae11a1959d679438e47da26d869d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
